### PR TITLE
Support keeping tas order after u-shaping

### PR DESCRIPTION
**Pull request by jrising**
This maintains the order of values coming out of u-shaped curves to match the temperatures that went in. This is needed for linear extrapolation. The default `ordered` argument is now set to `maintain` which has this functionality. 

I plan on removing the old functionality, and the `ordered` argument in the future, but it is useful now as a test of the new code.

### CODE REVIEW

**Comment by jrising** [comment]
@brews Do you know why the unit tests here are failing? The errors are coming from numpy and statsmodels.

**Comment by brews** [comment]
Yo James, I don't know that we've ever gotten these branches to build. On my quick look, CI doesn't show `linext-2.0` branch ever testing successfully...

Stop me if I'm wrong but I don't know that we cleaned up unit tests for this older branch. The focus was on `master`...? - stop me if I'm full of it.

Running this locally with a py2.7 env, I see lots of error I would have raised a stink about. Right off the plate I'm getting errors about modules not being in the path and such:

```
_______________________________________________________________ ERROR collecting test/models/test_combine.py _______________________________________________________________
ImportError while importing test module '/Users/bmalevich/Projects/open-estimate/test/models/test_combine.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/models/test_combine.py:4: in <module>
    from model import Model
E   ImportError: No module named model
____________________________________________________________ ERROR collecting test/models/test_distribution.py _____________________________________________________________
ImportError while importing test module '/Users/bmalevich/Projects/open-estimate/test/models/test_distribution.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/models/test_distribution.py:4: in <module>
    from ddp_model import DDPModel
E   ImportError: No module named ddp_model
_______________________________________________________________ ERROR collecting test/models/test_spline.py ________________________________________________________________
ImportError while importing test module '/Users/bmalevich/Projects/open-estimate/test/models/test_spline.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/models/test_spline.py:4: in <module>
    from spline_model import SplineModel
E   ImportError: No module named spline_model
```

I can review your changes, but I'd trust Dylan running this with the downstream changes over these unit tests passing.

**Comment by brews** [comment]
@jrising, can we delete this `origin/ordereducurve` branch now that is has merged? Is it still used for something?

Just a general cleanup thing. Not something that needs to happen immediately.

**Comment by jrising** [comment]
I was keeping it open because I reference it in https://gitlab.com/ClimateImpactLab/Impacts/impact-calculations/-/issues/107
Dylan is testing it, and might probably has a local `linext-2.0` branch that hasn't been affected. So, as soon as he's done testing `ordereducurve`, we can drop it.

**Pull request merged**
