### PR TITLE
Paired additions to support `wheaties` on `impact-calculations`

### PR DESCRIPTION
**Pull request by jrising**
This defines a new `SumByTimeCoefficientsCurve` needed for modelling wheat.

### CODE REVIEW

**Comment by jrising** [comment]
@brews For review with its sister branch.

**Review by brews — APPROVED** [review]
Cool. Thanks @jrising! I think this looks fine.

I wasn't able to run all the system tests on this and your proposed changes in `impact-calculations@wheaties`. Were you able to run all tests?

Some day all those references to `*._data` and other protected attributes are going to come back and bite us in the butt in the future. (Just a comment. This is, of course, not the time or place to deal with it.)

**Comment by jrising** [comment]
@brews I'm getting seg. faults when I try to run the system tests, even if I drop my new tests. I'm trying to track down if this is related to my changes or to edits to the Ag. climate inputs or to nothing at all.

**Comment by brews** [comment]
Yeah @jrising, I have been having sporadic trouble with netCDF IO over the last week/week-an-a-half with "wheaties" and the new clipping features. I played around with this today. I had folk move all the aggregation jobs over to `bat` or to `renice` their jobs. Then the changes in both PRs (new clipping and wheaties) passed. Failures might have be from extremely high traffic and/or maybe the LTS system upgrade...? Don't know for sure.

For wheaties:
```
...
  /home/bmalevich/Projects/wheaties/impact-calculations/tests/test_season_conditionals.py:83: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    config['models'][0]['specifications']['precip']['suffix-triangle'] = yaml.load(json_str)

tests/test_season_conditionals.py::test_condition
  /home/bmalevich/Projects/wheaties/impact-calculations/tests/test_season_conditionals.py:106: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    config['models'][0]['calculation'][0]['Sum'] = yaml.load(json_str)

tests/test_season_conditionals.py::test_gddsplit
  /home/bmalevich/Projects/wheaties/impact-calculations/tests/test_season_conditionals.py:149: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    gddkdd_fall = yaml.load(json_str1)

tests/test_season_conditionals.py::test_gddsplit
  /home/bmalevich/Projects/wheaties/impact-calculations/tests/test_season_conditionals.py:151: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    gddkdd_winter = yaml.load(json_str1)

tests/test_season_conditionals.py::test_gddsplit
  /home/bmalevich/Projects/wheaties/impact-calculations/tests/test_season_conditionals.py:153: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    gddkdd_summer = yaml.load(json_str1)

tests/test_season_conditionals.py::test_gddsplit
  /home/bmalevich/Projects/wheaties/impact-calculations/tests/test_season_conditionals.py:159: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    config['models'][0]['calculation'][0]['Sum'] = yaml.load(json_str2)

tests/test_weatherreader.py::TestWeatherReader::test_bincompare
  /home/bmalevich/miniconda3/envs/wheaties/lib/python3.7/site-packages/xarray/coding/times.py:219: FutureWarning: the 'box' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'box'
    result = pd.to_timedelta(num_timedeltas, unit=units, box=False)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
(wheaties test)==================== 162 passed, 4 skipped, 18 warnings in 9248.06s (2:34:08) ==============================
```

There are a few warnings on unsafe yaml loading, etc, but no failures. Now that I know the tests pass, I'll give a look at your changes downstream in `impact-calculations@wheaties` first thing tomorrow morning.

**Pull request merged**
