### PR TITLE
drop in replacement

### PR DESCRIPTION
**Pull request by emileten**
performance improvements similar to https://github.com/ClimateImpactLab/open-estimate/pull/54. profile description [here](https://gitlab.com/ClimateImpactLab/Impacts/impact-calculations/-/merge_requests/234).

### CODE REVIEW

**Comment by jrising** [comment]
Thanks for the updates! Why do you have the `bn`->`np` fallback only in `irregular.py`?

Are you able to merge? If not, I can do it.

**Comment by emileten** [comment]
Thanks @jrising. It was already there in `irregular.py` so I didn't have to add it. 

I cannot merge -- but maybe I should run the full tests with that change in the impacts repo ? I can pin you when it's done.

**Comment by jrising** [comment]
Do run the full tests, but I think it's fine to merge these now. I'll do it.

**Comment by emileten** [comment]
@jrising thanks. I confirm that both the impacts-repo full tests passed and the `test/generate` unit tests from here passed.

**Pull request merged**
